[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "feds-documentation"
authors = [{name = "Katrina Sharonin", email = "ksharonin@berkeley.edu"}]
dynamic = ["version", "description"]
